# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Yuxi Liu
first_name: Yuxi
middle_name: 
last_name: Liu
email: yuxiliu666@stu.pku.edu.cn
contact_note: >
  Ph.D. Student at Center for Machine Learning Research, Peking University.

description: >
  Yuxi Liu's Academic Homepage. Efficient training and inference frameworks/algorithms for LLM/DiT.

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

keywords: Yuxi Liu, Machine Learning, LLM, DiT, PKU, Mathematics
lang: en 
icon: ⚛️ 

url: https://yuxiliu.github.io 
baseurl: "" 
last_updated: true 
back_to_top: true 

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

external_services:
  github_readme_stats_url: https://github-readme-stats.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

max_width: 930px

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Yuxi's Blog
blog_description: Research and Thoughts.
permalink: /blog/:year/:title/

pagination:
  enabled: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
  teachings:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: [_pages, _scripts]
exclude:
  - bin
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives-v2
  - jekyll-cache-bust
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyllscholar
  - jekyll-sitemap
  - jekyll-socials
  - jemoji

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Liu]
  first_name: [Yuxi, Y.]

  style: apa
  locale: en

  source: _bibliography
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_math: true 
enable_darkmode: true 
enable_navbar_social: true 
enable_progressbar: true 

# -----------------------------------------------------------------------------
# Library versions (Keep as original)
# -----------------------------------------------------------------------------
third_party_libraries:
  download: false
  bootstrap-table:
    version: 1.22.4
  chartjs:
    version: 4.4.1
  d3:
    version: 7.8.5
